// Code generated by gen-accessors; DO NOT EDIT.

package servicenow

// GetActive returns the Active field if it's non-nil, zero value otherwise.
func (i *Incident) GetActive() string {
	if i == nil || i.Active == nil {
		return ""
	}
	return *i.Active
}

// GetActivityDue returns the ActivityDue field if it's non-nil, zero value otherwise.
func (i *Incident) GetActivityDue() string {
	if i == nil || i.ActivityDue == nil {
		return ""
	}
	return *i.ActivityDue
}

// GetAdditionalAssigneeList returns the AdditionalAssigneeList field if it's non-nil, zero value otherwise.
func (i *Incident) GetAdditionalAssigneeList() string {
	if i == nil || i.AdditionalAssigneeList == nil {
		return ""
	}
	return *i.AdditionalAssigneeList
}

// GetApproval returns the Approval field if it's non-nil, zero value otherwise.
func (i *Incident) GetApproval() string {
	if i == nil || i.Approval == nil {
		return ""
	}
	return *i.Approval
}

// GetApprovalHistory returns the ApprovalHistory field if it's non-nil, zero value otherwise.
func (i *Incident) GetApprovalHistory() string {
	if i == nil || i.ApprovalHistory == nil {
		return ""
	}
	return *i.ApprovalHistory
}

// GetApprovalSet returns the ApprovalSet field if it's non-nil, zero value otherwise.
func (i *Incident) GetApprovalSet() string {
	if i == nil || i.ApprovalSet == nil {
		return ""
	}
	return *i.ApprovalSet
}

// GetAssignedTo returns the AssignedTo field if it's non-nil, zero value otherwise.
func (i *Incident) GetAssignedTo() string {
	if i == nil || i.AssignedTo == nil {
		return ""
	}
	return *i.AssignedTo
}

// GetAssignmentGroup returns the AssignmentGroup field if it's non-nil, zero value otherwise.
func (i *Incident) GetAssignmentGroup() string {
	if i == nil || i.AssignmentGroup == nil {
		return ""
	}
	return *i.AssignmentGroup
}

// GetBusinessDuration returns the BusinessDuration field if it's non-nil, zero value otherwise.
func (i *Incident) GetBusinessDuration() string {
	if i == nil || i.BusinessDuration == nil {
		return ""
	}
	return *i.BusinessDuration
}

// GetBusinessService returns the BusinessService field if it's non-nil, zero value otherwise.
func (i *Incident) GetBusinessService() string {
	if i == nil || i.BusinessService == nil {
		return ""
	}
	return *i.BusinessService
}

// GetBusinessStc returns the BusinessStc field if it's non-nil, zero value otherwise.
func (i *Incident) GetBusinessStc() string {
	if i == nil || i.BusinessStc == nil {
		return ""
	}
	return *i.BusinessStc
}

// GetCalendarDuration returns the CalendarDuration field if it's non-nil, zero value otherwise.
func (i *Incident) GetCalendarDuration() string {
	if i == nil || i.CalendarDuration == nil {
		return ""
	}
	return *i.CalendarDuration
}

// GetCalendarStc returns the CalendarStc field if it's non-nil, zero value otherwise.
func (i *Incident) GetCalendarStc() string {
	if i == nil || i.CalendarStc == nil {
		return ""
	}
	return *i.CalendarStc
}

// GetCallerID returns the CallerID field if it's non-nil, zero value otherwise.
func (i *Incident) GetCallerID() string {
	if i == nil || i.CallerID == nil {
		return ""
	}
	return *i.CallerID
}

// GetCategory returns the Category field if it's non-nil, zero value otherwise.
func (i *Incident) GetCategory() string {
	if i == nil || i.Category == nil {
		return ""
	}
	return *i.Category
}

// GetCausedBy returns the CausedBy field if it's non-nil, zero value otherwise.
func (i *Incident) GetCausedBy() string {
	if i == nil || i.CausedBy == nil {
		return ""
	}
	return *i.CausedBy
}

// GetChildIncidents returns the ChildIncidents field if it's non-nil, zero value otherwise.
func (i *Incident) GetChildIncidents() string {
	if i == nil || i.ChildIncidents == nil {
		return ""
	}
	return *i.ChildIncidents
}

// GetCloseCode returns the CloseCode field if it's non-nil, zero value otherwise.
func (i *Incident) GetCloseCode() string {
	if i == nil || i.CloseCode == nil {
		return ""
	}
	return *i.CloseCode
}

// GetClosedAt returns the ClosedAt field if it's non-nil, zero value otherwise.
func (i *Incident) GetClosedAt() string {
	if i == nil || i.ClosedAt == nil {
		return ""
	}
	return *i.ClosedAt
}

// GetClosedBy returns the ClosedBy field if it's non-nil, zero value otherwise.
func (i *Incident) GetClosedBy() string {
	if i == nil || i.ClosedBy == nil {
		return ""
	}
	return *i.ClosedBy
}

// GetCloseNotes returns the CloseNotes field if it's non-nil, zero value otherwise.
func (i *Incident) GetCloseNotes() string {
	if i == nil || i.CloseNotes == nil {
		return ""
	}
	return *i.CloseNotes
}

// GetCmdbCi returns the CmdbCi field if it's non-nil, zero value otherwise.
func (i *Incident) GetCmdbCi() string {
	if i == nil || i.CmdbCi == nil {
		return ""
	}
	return *i.CmdbCi
}

// GetComments returns the Comments field if it's non-nil, zero value otherwise.
func (i *Incident) GetComments() string {
	if i == nil || i.Comments == nil {
		return ""
	}
	return *i.Comments
}

// GetCommentsAndWorkNotes returns the CommentsAndWorkNotes field if it's non-nil, zero value otherwise.
func (i *Incident) GetCommentsAndWorkNotes() string {
	if i == nil || i.CommentsAndWorkNotes == nil {
		return ""
	}
	return *i.CommentsAndWorkNotes
}

// GetCompany returns the Company field if it's non-nil, zero value otherwise.
func (i *Incident) GetCompany() string {
	if i == nil || i.Company == nil {
		return ""
	}
	return *i.Company
}

// GetContactType returns the ContactType field if it's non-nil, zero value otherwise.
func (i *Incident) GetContactType() string {
	if i == nil || i.ContactType == nil {
		return ""
	}
	return *i.ContactType
}

// GetCorrelationDisplay returns the CorrelationDisplay field if it's non-nil, zero value otherwise.
func (i *Incident) GetCorrelationDisplay() string {
	if i == nil || i.CorrelationDisplay == nil {
		return ""
	}
	return *i.CorrelationDisplay
}

// GetCorrelationID returns the CorrelationID field if it's non-nil, zero value otherwise.
func (i *Incident) GetCorrelationID() string {
	if i == nil || i.CorrelationID == nil {
		return ""
	}
	return *i.CorrelationID
}

// GetDeliveryPlan returns the DeliveryPlan field if it's non-nil, zero value otherwise.
func (i *Incident) GetDeliveryPlan() string {
	if i == nil || i.DeliveryPlan == nil {
		return ""
	}
	return *i.DeliveryPlan
}

// GetDeliveryTask returns the DeliveryTask field if it's non-nil, zero value otherwise.
func (i *Incident) GetDeliveryTask() string {
	if i == nil || i.DeliveryTask == nil {
		return ""
	}
	return *i.DeliveryTask
}

// GetDescription returns the Description field if it's non-nil, zero value otherwise.
func (i *Incident) GetDescription() string {
	if i == nil || i.Description == nil {
		return ""
	}
	return *i.Description
}

// GetDueDate returns the DueDate field if it's non-nil, zero value otherwise.
func (i *Incident) GetDueDate() string {
	if i == nil || i.DueDate == nil {
		return ""
	}
	return *i.DueDate
}

// GetEscalation returns the Escalation field if it's non-nil, zero value otherwise.
func (i *Incident) GetEscalation() string {
	if i == nil || i.Escalation == nil {
		return ""
	}
	return *i.Escalation
}

// GetExpectedStart returns the ExpectedStart field if it's non-nil, zero value otherwise.
func (i *Incident) GetExpectedStart() string {
	if i == nil || i.ExpectedStart == nil {
		return ""
	}
	return *i.ExpectedStart
}

// GetFollowUp returns the FollowUp field if it's non-nil, zero value otherwise.
func (i *Incident) GetFollowUp() string {
	if i == nil || i.FollowUp == nil {
		return ""
	}
	return *i.FollowUp
}

// GetGroupList returns the GroupList field if it's non-nil, zero value otherwise.
func (i *Incident) GetGroupList() string {
	if i == nil || i.GroupList == nil {
		return ""
	}
	return *i.GroupList
}

// GetImpact returns the Impact field if it's non-nil, zero value otherwise.
func (i *Incident) GetImpact() string {
	if i == nil || i.Impact == nil {
		return ""
	}
	return *i.Impact
}

// GetIncidentState returns the IncidentState field if it's non-nil, zero value otherwise.
func (i *Incident) GetIncidentState() string {
	if i == nil || i.IncidentState == nil {
		return ""
	}
	return *i.IncidentState
}

// GetKnowledge returns the Knowledge field if it's non-nil, zero value otherwise.
func (i *Incident) GetKnowledge() string {
	if i == nil || i.Knowledge == nil {
		return ""
	}
	return *i.Knowledge
}

// GetLocation returns the Location field if it's non-nil, zero value otherwise.
func (i *Incident) GetLocation() string {
	if i == nil || i.Location == nil {
		return ""
	}
	return *i.Location
}

// GetMadeSLA returns the MadeSLA field if it's non-nil, zero value otherwise.
func (i *Incident) GetMadeSLA() string {
	if i == nil || i.MadeSLA == nil {
		return ""
	}
	return *i.MadeSLA
}

// GetNotify returns the Notify field if it's non-nil, zero value otherwise.
func (i *Incident) GetNotify() string {
	if i == nil || i.Notify == nil {
		return ""
	}
	return *i.Notify
}

// GetNumber returns the Number field if it's non-nil, zero value otherwise.
func (i *Incident) GetNumber() string {
	if i == nil || i.Number == nil {
		return ""
	}
	return *i.Number
}

// GetOpenedAt returns the OpenedAt field if it's non-nil, zero value otherwise.
func (i *Incident) GetOpenedAt() string {
	if i == nil || i.OpenedAt == nil {
		return ""
	}
	return *i.OpenedAt
}

// GetOpenedBy returns the OpenedBy field if it's non-nil, zero value otherwise.
func (i *Incident) GetOpenedBy() string {
	if i == nil || i.OpenedBy == nil {
		return ""
	}
	return *i.OpenedBy
}

// GetOrder returns the Order field if it's non-nil, zero value otherwise.
func (i *Incident) GetOrder() string {
	if i == nil || i.Order == nil {
		return ""
	}
	return *i.Order
}

// GetParent returns the Parent field if it's non-nil, zero value otherwise.
func (i *Incident) GetParent() string {
	if i == nil || i.Parent == nil {
		return ""
	}
	return *i.Parent
}

// GetParentIncident returns the ParentIncident field if it's non-nil, zero value otherwise.
func (i *Incident) GetParentIncident() string {
	if i == nil || i.ParentIncident == nil {
		return ""
	}
	return *i.ParentIncident
}

// GetPriority returns the Priority field if it's non-nil, zero value otherwise.
func (i *Incident) GetPriority() string {
	if i == nil || i.Priority == nil {
		return ""
	}
	return *i.Priority
}

// GetProblemID returns the ProblemID field if it's non-nil, zero value otherwise.
func (i *Incident) GetProblemID() string {
	if i == nil || i.ProblemID == nil {
		return ""
	}
	return *i.ProblemID
}

// GetReassignmentCount returns the ReassignmentCount field if it's non-nil, zero value otherwise.
func (i *Incident) GetReassignmentCount() string {
	if i == nil || i.ReassignmentCount == nil {
		return ""
	}
	return *i.ReassignmentCount
}

// GetRejectionGoto returns the RejectionGoto field if it's non-nil, zero value otherwise.
func (i *Incident) GetRejectionGoto() string {
	if i == nil || i.RejectionGoto == nil {
		return ""
	}
	return *i.RejectionGoto
}

// GetReopenCount returns the ReopenCount field if it's non-nil, zero value otherwise.
func (i *Incident) GetReopenCount() string {
	if i == nil || i.ReopenCount == nil {
		return ""
	}
	return *i.ReopenCount
}

// GetResolvedAt returns the ResolvedAt field if it's non-nil, zero value otherwise.
func (i *Incident) GetResolvedAt() string {
	if i == nil || i.ResolvedAt == nil {
		return ""
	}
	return *i.ResolvedAt
}

// GetResolvedBy returns the ResolvedBy field if it's non-nil, zero value otherwise.
func (i *Incident) GetResolvedBy() string {
	if i == nil || i.ResolvedBy == nil {
		return ""
	}
	return *i.ResolvedBy
}

// GetRfc returns the Rfc field if it's non-nil, zero value otherwise.
func (i *Incident) GetRfc() string {
	if i == nil || i.Rfc == nil {
		return ""
	}
	return *i.Rfc
}

// GetSeverity returns the Severity field if it's non-nil, zero value otherwise.
func (i *Incident) GetSeverity() string {
	if i == nil || i.Severity == nil {
		return ""
	}
	return *i.Severity
}

// GetShortDescription returns the ShortDescription field if it's non-nil, zero value otherwise.
func (i *Incident) GetShortDescription() string {
	if i == nil || i.ShortDescription == nil {
		return ""
	}
	return *i.ShortDescription
}

// GetSLADue returns the SLADue field if it's non-nil, zero value otherwise.
func (i *Incident) GetSLADue() string {
	if i == nil || i.SLADue == nil {
		return ""
	}
	return *i.SLADue
}

// GetState returns the State field if it's non-nil, zero value otherwise.
func (i *Incident) GetState() string {
	if i == nil || i.State == nil {
		return ""
	}
	return *i.State
}

// GetStatus returns the Status field if it's non-nil, zero value otherwise.
func (i *Incident) GetStatus() string {
	if i == nil || i.Status == nil {
		return ""
	}
	return *i.Status
}

// GetSubcategory returns the Subcategory field if it's non-nil, zero value otherwise.
func (i *Incident) GetSubcategory() string {
	if i == nil || i.Subcategory == nil {
		return ""
	}
	return *i.Subcategory
}

// GetSysClassName returns the SysClassName field if it's non-nil, zero value otherwise.
func (i *Incident) GetSysClassName() string {
	if i == nil || i.SysClassName == nil {
		return ""
	}
	return *i.SysClassName
}

// GetSysCreatedBy returns the SysCreatedBy field if it's non-nil, zero value otherwise.
func (i *Incident) GetSysCreatedBy() string {
	if i == nil || i.SysCreatedBy == nil {
		return ""
	}
	return *i.SysCreatedBy
}

// GetSysCreatedOn returns the SysCreatedOn field if it's non-nil, zero value otherwise.
func (i *Incident) GetSysCreatedOn() string {
	if i == nil || i.SysCreatedOn == nil {
		return ""
	}
	return *i.SysCreatedOn
}

// GetSysDomain returns the SysDomain field if it's non-nil, zero value otherwise.
func (i *Incident) GetSysDomain() string {
	if i == nil || i.SysDomain == nil {
		return ""
	}
	return *i.SysDomain
}

// GetSysDomainPath returns the SysDomainPath field if it's non-nil, zero value otherwise.
func (i *Incident) GetSysDomainPath() string {
	if i == nil || i.SysDomainPath == nil {
		return ""
	}
	return *i.SysDomainPath
}

// GetSysID returns the SysID field if it's non-nil, zero value otherwise.
func (i *Incident) GetSysID() string {
	if i == nil || i.SysID == nil {
		return ""
	}
	return *i.SysID
}

// GetSysModCount returns the SysModCount field if it's non-nil, zero value otherwise.
func (i *Incident) GetSysModCount() string {
	if i == nil || i.SysModCount == nil {
		return ""
	}
	return *i.SysModCount
}

// GetSysTags returns the SysTags field if it's non-nil, zero value otherwise.
func (i *Incident) GetSysTags() string {
	if i == nil || i.SysTags == nil {
		return ""
	}
	return *i.SysTags
}

// GetSysUpdatedBy returns the SysUpdatedBy field if it's non-nil, zero value otherwise.
func (i *Incident) GetSysUpdatedBy() string {
	if i == nil || i.SysUpdatedBy == nil {
		return ""
	}
	return *i.SysUpdatedBy
}

// GetSysUpdatedOn returns the SysUpdatedOn field if it's non-nil, zero value otherwise.
func (i *Incident) GetSysUpdatedOn() string {
	if i == nil || i.SysUpdatedOn == nil {
		return ""
	}
	return *i.SysUpdatedOn
}

// GetTimeWorked returns the TimeWorked field if it's non-nil, zero value otherwise.
func (i *Incident) GetTimeWorked() string {
	if i == nil || i.TimeWorked == nil {
		return ""
	}
	return *i.TimeWorked
}

// GetUponApproval returns the UponApproval field if it's non-nil, zero value otherwise.
func (i *Incident) GetUponApproval() string {
	if i == nil || i.UponApproval == nil {
		return ""
	}
	return *i.UponApproval
}

// GetUponReject returns the UponReject field if it's non-nil, zero value otherwise.
func (i *Incident) GetUponReject() string {
	if i == nil || i.UponReject == nil {
		return ""
	}
	return *i.UponReject
}

// GetUrgency returns the Urgency field if it's non-nil, zero value otherwise.
func (i *Incident) GetUrgency() string {
	if i == nil || i.Urgency == nil {
		return ""
	}
	return *i.Urgency
}

// GetUserInput returns the UserInput field if it's non-nil, zero value otherwise.
func (i *Incident) GetUserInput() string {
	if i == nil || i.UserInput == nil {
		return ""
	}
	return *i.UserInput
}

// GetWatchList returns the WatchList field if it's non-nil, zero value otherwise.
func (i *Incident) GetWatchList() string {
	if i == nil || i.WatchList == nil {
		return ""
	}
	return *i.WatchList
}

// GetWfActivity returns the WfActivity field if it's non-nil, zero value otherwise.
func (i *Incident) GetWfActivity() string {
	if i == nil || i.WfActivity == nil {
		return ""
	}
	return *i.WfActivity
}

// GetWorkEnd returns the WorkEnd field if it's non-nil, zero value otherwise.
func (i *Incident) GetWorkEnd() string {
	if i == nil || i.WorkEnd == nil {
		return ""
	}
	return *i.WorkEnd
}

// GetWorkNotes returns the WorkNotes field if it's non-nil, zero value otherwise.
func (i *Incident) GetWorkNotes() string {
	if i == nil || i.WorkNotes == nil {
		return ""
	}
	return *i.WorkNotes
}

// GetWorkNotesList returns the WorkNotesList field if it's non-nil, zero value otherwise.
func (i *Incident) GetWorkNotesList() string {
	if i == nil || i.WorkNotesList == nil {
		return ""
	}
	return *i.WorkNotesList
}

// GetWorkStart returns the WorkStart field if it's non-nil, zero value otherwise.
func (i *Incident) GetWorkStart() string {
	if i == nil || i.WorkStart == nil {
		return ""
	}
	return *i.WorkStart
}
