// Code generated by gen-accessors; DO NOT EDIT.

package servicenow

// GetActive returns the Active field if it's non-nil, zero value otherwise.
func (c *ChangeRequest) GetActive() string {
	if c == nil || c.Active == nil {
		return ""
	}
	return *c.Active
}

// GetActivityDue returns the ActivityDue field if it's non-nil, zero value otherwise.
func (c *ChangeRequest) GetActivityDue() string {
	if c == nil || c.ActivityDue == nil {
		return ""
	}
	return *c.ActivityDue
}

// GetAdditionalAssigneeList returns the AdditionalAssigneeList field if it's non-nil, zero value otherwise.
func (c *ChangeRequest) GetAdditionalAssigneeList() string {
	if c == nil || c.AdditionalAssigneeList == nil {
		return ""
	}
	return *c.AdditionalAssigneeList
}

// GetApproval returns the Approval field if it's non-nil, zero value otherwise.
func (c *ChangeRequest) GetApproval() string {
	if c == nil || c.Approval == nil {
		return ""
	}
	return *c.Approval
}

// GetApprovalHistory returns the ApprovalHistory field if it's non-nil, zero value otherwise.
func (c *ChangeRequest) GetApprovalHistory() string {
	if c == nil || c.ApprovalHistory == nil {
		return ""
	}
	return *c.ApprovalHistory
}

// GetApprovalSet returns the ApprovalSet field if it's non-nil, zero value otherwise.
func (c *ChangeRequest) GetApprovalSet() string {
	if c == nil || c.ApprovalSet == nil {
		return ""
	}
	return *c.ApprovalSet
}

// GetAssignedTo returns the AssignedTo field if it's non-nil, zero value otherwise.
func (c *ChangeRequest) GetAssignedTo() string {
	if c == nil || c.AssignedTo == nil {
		return ""
	}
	return *c.AssignedTo
}

// GetAssignmentGroup returns the AssignmentGroup field if it's non-nil, zero value otherwise.
func (c *ChangeRequest) GetAssignmentGroup() string {
	if c == nil || c.AssignmentGroup == nil {
		return ""
	}
	return *c.AssignmentGroup
}

// GetBackoutPlan returns the BackoutPlan field if it's non-nil, zero value otherwise.
func (c *ChangeRequest) GetBackoutPlan() string {
	if c == nil || c.BackoutPlan == nil {
		return ""
	}
	return *c.BackoutPlan
}

// GetBusinessDuration returns the BusinessDuration field if it's non-nil, zero value otherwise.
func (c *ChangeRequest) GetBusinessDuration() string {
	if c == nil || c.BusinessDuration == nil {
		return ""
	}
	return *c.BusinessDuration
}

// GetBusinessService returns the BusinessService field if it's non-nil, zero value otherwise.
func (c *ChangeRequest) GetBusinessService() string {
	if c == nil || c.BusinessService == nil {
		return ""
	}
	return *c.BusinessService
}

// GetCabDate returns the CabDate field if it's non-nil, zero value otherwise.
func (c *ChangeRequest) GetCabDate() string {
	if c == nil || c.CabDate == nil {
		return ""
	}
	return *c.CabDate
}

// GetCabDelegate returns the CabDelegate field if it's non-nil, zero value otherwise.
func (c *ChangeRequest) GetCabDelegate() string {
	if c == nil || c.CabDelegate == nil {
		return ""
	}
	return *c.CabDelegate
}

// GetCabRecommendation returns the CabRecommendation field if it's non-nil, zero value otherwise.
func (c *ChangeRequest) GetCabRecommendation() string {
	if c == nil || c.CabRecommendation == nil {
		return ""
	}
	return *c.CabRecommendation
}

// GetCabRequired returns the CabRequired field if it's non-nil, zero value otherwise.
func (c *ChangeRequest) GetCabRequired() string {
	if c == nil || c.CabRequired == nil {
		return ""
	}
	return *c.CabRequired
}

// GetCalendarDuration returns the CalendarDuration field if it's non-nil, zero value otherwise.
func (c *ChangeRequest) GetCalendarDuration() string {
	if c == nil || c.CalendarDuration == nil {
		return ""
	}
	return *c.CalendarDuration
}

// GetCategory returns the Category field if it's non-nil, zero value otherwise.
func (c *ChangeRequest) GetCategory() string {
	if c == nil || c.Category == nil {
		return ""
	}
	return *c.Category
}

// GetChangePlan returns the ChangePlan field if it's non-nil, zero value otherwise.
func (c *ChangeRequest) GetChangePlan() string {
	if c == nil || c.ChangePlan == nil {
		return ""
	}
	return *c.ChangePlan
}

// GetChgModel returns the ChgModel field if it's non-nil, zero value otherwise.
func (c *ChangeRequest) GetChgModel() string {
	if c == nil || c.ChgModel == nil {
		return ""
	}
	return *c.ChgModel
}

// GetCloseCode returns the CloseCode field if it's non-nil, zero value otherwise.
func (c *ChangeRequest) GetCloseCode() string {
	if c == nil || c.CloseCode == nil {
		return ""
	}
	return *c.CloseCode
}

// GetClosedAt returns the ClosedAt field if it's non-nil, zero value otherwise.
func (c *ChangeRequest) GetClosedAt() string {
	if c == nil || c.ClosedAt == nil {
		return ""
	}
	return *c.ClosedAt
}

// GetClosedBy returns the ClosedBy field if it's non-nil, zero value otherwise.
func (c *ChangeRequest) GetClosedBy() string {
	if c == nil || c.ClosedBy == nil {
		return ""
	}
	return *c.ClosedBy
}

// GetCloseNotes returns the CloseNotes field if it's non-nil, zero value otherwise.
func (c *ChangeRequest) GetCloseNotes() string {
	if c == nil || c.CloseNotes == nil {
		return ""
	}
	return *c.CloseNotes
}

// GetCmdbCi returns the CmdbCi field if it's non-nil, zero value otherwise.
func (c *ChangeRequest) GetCmdbCi() string {
	if c == nil || c.CmdbCi == nil {
		return ""
	}
	return *c.CmdbCi
}

// GetComments returns the Comments field if it's non-nil, zero value otherwise.
func (c *ChangeRequest) GetComments() string {
	if c == nil || c.Comments == nil {
		return ""
	}
	return *c.Comments
}

// GetCommentsAndWorkNotes returns the CommentsAndWorkNotes field if it's non-nil, zero value otherwise.
func (c *ChangeRequest) GetCommentsAndWorkNotes() string {
	if c == nil || c.CommentsAndWorkNotes == nil {
		return ""
	}
	return *c.CommentsAndWorkNotes
}

// GetCompany returns the Company field if it's non-nil, zero value otherwise.
func (c *ChangeRequest) GetCompany() string {
	if c == nil || c.Company == nil {
		return ""
	}
	return *c.Company
}

// GetConflictLastRun returns the ConflictLastRun field if it's non-nil, zero value otherwise.
func (c *ChangeRequest) GetConflictLastRun() string {
	if c == nil || c.ConflictLastRun == nil {
		return ""
	}
	return *c.ConflictLastRun
}

// GetConflictStatus returns the ConflictStatus field if it's non-nil, zero value otherwise.
func (c *ChangeRequest) GetConflictStatus() string {
	if c == nil || c.ConflictStatus == nil {
		return ""
	}
	return *c.ConflictStatus
}

// GetContactType returns the ContactType field if it's non-nil, zero value otherwise.
func (c *ChangeRequest) GetContactType() string {
	if c == nil || c.ContactType == nil {
		return ""
	}
	return *c.ContactType
}

// GetCorrelationDisplay returns the CorrelationDisplay field if it's non-nil, zero value otherwise.
func (c *ChangeRequest) GetCorrelationDisplay() string {
	if c == nil || c.CorrelationDisplay == nil {
		return ""
	}
	return *c.CorrelationDisplay
}

// GetCorrelationID returns the CorrelationID field if it's non-nil, zero value otherwise.
func (c *ChangeRequest) GetCorrelationID() string {
	if c == nil || c.CorrelationID == nil {
		return ""
	}
	return *c.CorrelationID
}

// GetDescription returns the Description field if it's non-nil, zero value otherwise.
func (c *ChangeRequest) GetDescription() string {
	if c == nil || c.Description == nil {
		return ""
	}
	return *c.Description
}

// GetDueDate returns the DueDate field if it's non-nil, zero value otherwise.
func (c *ChangeRequest) GetDueDate() string {
	if c == nil || c.DueDate == nil {
		return ""
	}
	return *c.DueDate
}

// GetEndDate returns the EndDate field if it's non-nil, zero value otherwise.
func (c *ChangeRequest) GetEndDate() string {
	if c == nil || c.EndDate == nil {
		return ""
	}
	return *c.EndDate
}

// GetEscalation returns the Escalation field if it's non-nil, zero value otherwise.
func (c *ChangeRequest) GetEscalation() string {
	if c == nil || c.Escalation == nil {
		return ""
	}
	return *c.Escalation
}

// GetExpectedStart returns the ExpectedStart field if it's non-nil, zero value otherwise.
func (c *ChangeRequest) GetExpectedStart() string {
	if c == nil || c.ExpectedStart == nil {
		return ""
	}
	return *c.ExpectedStart
}

// GetFollowUp returns the FollowUp field if it's non-nil, zero value otherwise.
func (c *ChangeRequest) GetFollowUp() string {
	if c == nil || c.FollowUp == nil {
		return ""
	}
	return *c.FollowUp
}

// GetGroupList returns the GroupList field if it's non-nil, zero value otherwise.
func (c *ChangeRequest) GetGroupList() string {
	if c == nil || c.GroupList == nil {
		return ""
	}
	return *c.GroupList
}

// GetImpact returns the Impact field if it's non-nil, zero value otherwise.
func (c *ChangeRequest) GetImpact() string {
	if c == nil || c.Impact == nil {
		return ""
	}
	return *c.Impact
}

// GetImplementationPlan returns the ImplementationPlan field if it's non-nil, zero value otherwise.
func (c *ChangeRequest) GetImplementationPlan() string {
	if c == nil || c.ImplementationPlan == nil {
		return ""
	}
	return *c.ImplementationPlan
}

// GetJustification returns the Justification field if it's non-nil, zero value otherwise.
func (c *ChangeRequest) GetJustification() string {
	if c == nil || c.Justification == nil {
		return ""
	}
	return *c.Justification
}

// GetKnowledge returns the Knowledge field if it's non-nil, zero value otherwise.
func (c *ChangeRequest) GetKnowledge() string {
	if c == nil || c.Knowledge == nil {
		return ""
	}
	return *c.Knowledge
}

// GetLocation returns the Location field if it's non-nil, zero value otherwise.
func (c *ChangeRequest) GetLocation() string {
	if c == nil || c.Location == nil {
		return ""
	}
	return *c.Location
}

// GetMadeSLA returns the MadeSLA field if it's non-nil, zero value otherwise.
func (c *ChangeRequest) GetMadeSLA() string {
	if c == nil || c.MadeSLA == nil {
		return ""
	}
	return *c.MadeSLA
}

// GetNumber returns the Number field if it's non-nil, zero value otherwise.
func (c *ChangeRequest) GetNumber() string {
	if c == nil || c.Number == nil {
		return ""
	}
	return *c.Number
}

// GetOnHold returns the OnHold field if it's non-nil, zero value otherwise.
func (c *ChangeRequest) GetOnHold() string {
	if c == nil || c.OnHold == nil {
		return ""
	}
	return *c.OnHold
}

// GetOnHoldReason returns the OnHoldReason field if it's non-nil, zero value otherwise.
func (c *ChangeRequest) GetOnHoldReason() string {
	if c == nil || c.OnHoldReason == nil {
		return ""
	}
	return *c.OnHoldReason
}

// GetOnHoldTask returns the OnHoldTask field if it's non-nil, zero value otherwise.
func (c *ChangeRequest) GetOnHoldTask() string {
	if c == nil || c.OnHoldTask == nil {
		return ""
	}
	return *c.OnHoldTask
}

// GetOpenedAt returns the OpenedAt field if it's non-nil, zero value otherwise.
func (c *ChangeRequest) GetOpenedAt() string {
	if c == nil || c.OpenedAt == nil {
		return ""
	}
	return *c.OpenedAt
}

// GetOpenedBy returns the OpenedBy field if it's non-nil, zero value otherwise.
func (c *ChangeRequest) GetOpenedBy() string {
	if c == nil || c.OpenedBy == nil {
		return ""
	}
	return *c.OpenedBy
}

// GetOrder returns the Order field if it's non-nil, zero value otherwise.
func (c *ChangeRequest) GetOrder() string {
	if c == nil || c.Order == nil {
		return ""
	}
	return *c.Order
}

// GetOutsideMaintenanceSchedule returns the OutsideMaintenanceSchedule field if it's non-nil, zero value otherwise.
func (c *ChangeRequest) GetOutsideMaintenanceSchedule() string {
	if c == nil || c.OutsideMaintenanceSchedule == nil {
		return ""
	}
	return *c.OutsideMaintenanceSchedule
}

// GetParent returns the Parent field if it's non-nil, zero value otherwise.
func (c *ChangeRequest) GetParent() string {
	if c == nil || c.Parent == nil {
		return ""
	}
	return *c.Parent
}

// GetPhase returns the Phase field if it's non-nil, zero value otherwise.
func (c *ChangeRequest) GetPhase() string {
	if c == nil || c.Phase == nil {
		return ""
	}
	return *c.Phase
}

// GetPhaseState returns the PhaseState field if it's non-nil, zero value otherwise.
func (c *ChangeRequest) GetPhaseState() string {
	if c == nil || c.PhaseState == nil {
		return ""
	}
	return *c.PhaseState
}

// GetPriority returns the Priority field if it's non-nil, zero value otherwise.
func (c *ChangeRequest) GetPriority() string {
	if c == nil || c.Priority == nil {
		return ""
	}
	return *c.Priority
}

// GetProductionSystem returns the ProductionSystem field if it's non-nil, zero value otherwise.
func (c *ChangeRequest) GetProductionSystem() string {
	if c == nil || c.ProductionSystem == nil {
		return ""
	}
	return *c.ProductionSystem
}

// GetReason returns the Reason field if it's non-nil, zero value otherwise.
func (c *ChangeRequest) GetReason() string {
	if c == nil || c.Reason == nil {
		return ""
	}
	return *c.Reason
}

// GetReassignmentCount returns the ReassignmentCount field if it's non-nil, zero value otherwise.
func (c *ChangeRequest) GetReassignmentCount() string {
	if c == nil || c.ReassignmentCount == nil {
		return ""
	}
	return *c.ReassignmentCount
}

// GetRequestedBy returns the RequestedBy field if it's non-nil, zero value otherwise.
func (c *ChangeRequest) GetRequestedBy() string {
	if c == nil || c.RequestedBy == nil {
		return ""
	}
	return *c.RequestedBy
}

// GetRequestedByDate returns the RequestedByDate field if it's non-nil, zero value otherwise.
func (c *ChangeRequest) GetRequestedByDate() string {
	if c == nil || c.RequestedByDate == nil {
		return ""
	}
	return *c.RequestedByDate
}

// GetReviewComments returns the ReviewComments field if it's non-nil, zero value otherwise.
func (c *ChangeRequest) GetReviewComments() string {
	if c == nil || c.ReviewComments == nil {
		return ""
	}
	return *c.ReviewComments
}

// GetReviewDate returns the ReviewDate field if it's non-nil, zero value otherwise.
func (c *ChangeRequest) GetReviewDate() string {
	if c == nil || c.ReviewDate == nil {
		return ""
	}
	return *c.ReviewDate
}

// GetReviewStatus returns the ReviewStatus field if it's non-nil, zero value otherwise.
func (c *ChangeRequest) GetReviewStatus() string {
	if c == nil || c.ReviewStatus == nil {
		return ""
	}
	return *c.ReviewStatus
}

// GetRisk returns the Risk field if it's non-nil, zero value otherwise.
func (c *ChangeRequest) GetRisk() string {
	if c == nil || c.Risk == nil {
		return ""
	}
	return *c.Risk
}

// GetRiskImpactAnalysis returns the RiskImpactAnalysis field if it's non-nil, zero value otherwise.
func (c *ChangeRequest) GetRiskImpactAnalysis() string {
	if c == nil || c.RiskImpactAnalysis == nil {
		return ""
	}
	return *c.RiskImpactAnalysis
}

// GetRiskValue returns the RiskValue field if it's non-nil, zero value otherwise.
func (c *ChangeRequest) GetRiskValue() string {
	if c == nil || c.RiskValue == nil {
		return ""
	}
	return *c.RiskValue
}

// GetRouteReason returns the RouteReason field if it's non-nil, zero value otherwise.
func (c *ChangeRequest) GetRouteReason() string {
	if c == nil || c.RouteReason == nil {
		return ""
	}
	return *c.RouteReason
}

// GetScope returns the Scope field if it's non-nil, zero value otherwise.
func (c *ChangeRequest) GetScope() string {
	if c == nil || c.Scope == nil {
		return ""
	}
	return *c.Scope
}

// GetServiceOffering returns the ServiceOffering field if it's non-nil, zero value otherwise.
func (c *ChangeRequest) GetServiceOffering() string {
	if c == nil || c.ServiceOffering == nil {
		return ""
	}
	return *c.ServiceOffering
}

// GetShortDescription returns the ShortDescription field if it's non-nil, zero value otherwise.
func (c *ChangeRequest) GetShortDescription() string {
	if c == nil || c.ShortDescription == nil {
		return ""
	}
	return *c.ShortDescription
}

// GetSkills returns the Skills field if it's non-nil, zero value otherwise.
func (c *ChangeRequest) GetSkills() string {
	if c == nil || c.Skills == nil {
		return ""
	}
	return *c.Skills
}

// GetSLADue returns the SLADue field if it's non-nil, zero value otherwise.
func (c *ChangeRequest) GetSLADue() string {
	if c == nil || c.SLADue == nil {
		return ""
	}
	return *c.SLADue
}

// GetSnEsignDocument returns the SnEsignDocument field if it's non-nil, zero value otherwise.
func (c *ChangeRequest) GetSnEsignDocument() string {
	if c == nil || c.SnEsignDocument == nil {
		return ""
	}
	return *c.SnEsignDocument
}

// GetSnEsignEsignatureConfiguration returns the SnEsignEsignatureConfiguration field if it's non-nil, zero value otherwise.
func (c *ChangeRequest) GetSnEsignEsignatureConfiguration() string {
	if c == nil || c.SnEsignEsignatureConfiguration == nil {
		return ""
	}
	return *c.SnEsignEsignatureConfiguration
}

// GetStartDate returns the StartDate field if it's non-nil, zero value otherwise.
func (c *ChangeRequest) GetStartDate() string {
	if c == nil || c.StartDate == nil {
		return ""
	}
	return *c.StartDate
}

// GetState returns the State field if it's non-nil, zero value otherwise.
func (c *ChangeRequest) GetState() string {
	if c == nil || c.State == nil {
		return ""
	}
	return *c.State
}

// GetStatus returns the Status field if it's non-nil, zero value otherwise.
func (c *ChangeRequest) GetStatus() string {
	if c == nil || c.Status == nil {
		return ""
	}
	return *c.Status
}

// GetStdChangeProducerVersion returns the StdChangeProducerVersion field if it's non-nil, zero value otherwise.
func (c *ChangeRequest) GetStdChangeProducerVersion() string {
	if c == nil || c.StdChangeProducerVersion == nil {
		return ""
	}
	return *c.StdChangeProducerVersion
}

// GetSysClassName returns the SysClassName field if it's non-nil, zero value otherwise.
func (c *ChangeRequest) GetSysClassName() string {
	if c == nil || c.SysClassName == nil {
		return ""
	}
	return *c.SysClassName
}

// GetSysCreatedBy returns the SysCreatedBy field if it's non-nil, zero value otherwise.
func (c *ChangeRequest) GetSysCreatedBy() string {
	if c == nil || c.SysCreatedBy == nil {
		return ""
	}
	return *c.SysCreatedBy
}

// GetSysCreatedOn returns the SysCreatedOn field if it's non-nil, zero value otherwise.
func (c *ChangeRequest) GetSysCreatedOn() string {
	if c == nil || c.SysCreatedOn == nil {
		return ""
	}
	return *c.SysCreatedOn
}

// GetSysDomain returns the SysDomain field if it's non-nil, zero value otherwise.
func (c *ChangeRequest) GetSysDomain() string {
	if c == nil || c.SysDomain == nil {
		return ""
	}
	return *c.SysDomain
}

// GetSysDomainPath returns the SysDomainPath field if it's non-nil, zero value otherwise.
func (c *ChangeRequest) GetSysDomainPath() string {
	if c == nil || c.SysDomainPath == nil {
		return ""
	}
	return *c.SysDomainPath
}

// GetSysID returns the SysID field if it's non-nil, zero value otherwise.
func (c *ChangeRequest) GetSysID() string {
	if c == nil || c.SysID == nil {
		return ""
	}
	return *c.SysID
}

// GetSysModCount returns the SysModCount field if it's non-nil, zero value otherwise.
func (c *ChangeRequest) GetSysModCount() string {
	if c == nil || c.SysModCount == nil {
		return ""
	}
	return *c.SysModCount
}

// GetSysTags returns the SysTags field if it's non-nil, zero value otherwise.
func (c *ChangeRequest) GetSysTags() string {
	if c == nil || c.SysTags == nil {
		return ""
	}
	return *c.SysTags
}

// GetSysUpdatedBy returns the SysUpdatedBy field if it's non-nil, zero value otherwise.
func (c *ChangeRequest) GetSysUpdatedBy() string {
	if c == nil || c.SysUpdatedBy == nil {
		return ""
	}
	return *c.SysUpdatedBy
}

// GetSysUpdatedOn returns the SysUpdatedOn field if it's non-nil, zero value otherwise.
func (c *ChangeRequest) GetSysUpdatedOn() string {
	if c == nil || c.SysUpdatedOn == nil {
		return ""
	}
	return *c.SysUpdatedOn
}

// GetTaskEffectiveNumber returns the TaskEffectiveNumber field if it's non-nil, zero value otherwise.
func (c *ChangeRequest) GetTaskEffectiveNumber() string {
	if c == nil || c.TaskEffectiveNumber == nil {
		return ""
	}
	return *c.TaskEffectiveNumber
}

// GetTestPlan returns the TestPlan field if it's non-nil, zero value otherwise.
func (c *ChangeRequest) GetTestPlan() string {
	if c == nil || c.TestPlan == nil {
		return ""
	}
	return *c.TestPlan
}

// GetTimeWorked returns the TimeWorked field if it's non-nil, zero value otherwise.
func (c *ChangeRequest) GetTimeWorked() string {
	if c == nil || c.TimeWorked == nil {
		return ""
	}
	return *c.TimeWorked
}

// GetType returns the Type field if it's non-nil, zero value otherwise.
func (c *ChangeRequest) GetType() string {
	if c == nil || c.Type == nil {
		return ""
	}
	return *c.Type
}

// GetUnauthorized returns the Unauthorized field if it's non-nil, zero value otherwise.
func (c *ChangeRequest) GetUnauthorized() string {
	if c == nil || c.Unauthorized == nil {
		return ""
	}
	return *c.Unauthorized
}

// GetUniversalRequest returns the UniversalRequest field if it's non-nil, zero value otherwise.
func (c *ChangeRequest) GetUniversalRequest() string {
	if c == nil || c.UniversalRequest == nil {
		return ""
	}
	return *c.UniversalRequest
}

// GetUponApproval returns the UponApproval field if it's non-nil, zero value otherwise.
func (c *ChangeRequest) GetUponApproval() string {
	if c == nil || c.UponApproval == nil {
		return ""
	}
	return *c.UponApproval
}

// GetUponReject returns the UponReject field if it's non-nil, zero value otherwise.
func (c *ChangeRequest) GetUponReject() string {
	if c == nil || c.UponReject == nil {
		return ""
	}
	return *c.UponReject
}

// GetUrgency returns the Urgency field if it's non-nil, zero value otherwise.
func (c *ChangeRequest) GetUrgency() string {
	if c == nil || c.Urgency == nil {
		return ""
	}
	return *c.Urgency
}

// GetUserInput returns the UserInput field if it's non-nil, zero value otherwise.
func (c *ChangeRequest) GetUserInput() string {
	if c == nil || c.UserInput == nil {
		return ""
	}
	return *c.UserInput
}

// GetWatchList returns the WatchList field if it's non-nil, zero value otherwise.
func (c *ChangeRequest) GetWatchList() string {
	if c == nil || c.WatchList == nil {
		return ""
	}
	return *c.WatchList
}

// GetWorkEnd returns the WorkEnd field if it's non-nil, zero value otherwise.
func (c *ChangeRequest) GetWorkEnd() string {
	if c == nil || c.WorkEnd == nil {
		return ""
	}
	return *c.WorkEnd
}

// GetWorkNotes returns the WorkNotes field if it's non-nil, zero value otherwise.
func (c *ChangeRequest) GetWorkNotes() string {
	if c == nil || c.WorkNotes == nil {
		return ""
	}
	return *c.WorkNotes
}

// GetWorkNotesList returns the WorkNotesList field if it's non-nil, zero value otherwise.
func (c *ChangeRequest) GetWorkNotesList() string {
	if c == nil || c.WorkNotesList == nil {
		return ""
	}
	return *c.WorkNotesList
}

// GetWorkStart returns the WorkStart field if it's non-nil, zero value otherwise.
func (c *ChangeRequest) GetWorkStart() string {
	if c == nil || c.WorkStart == nil {
		return ""
	}
	return *c.WorkStart
}

// GetActive returns the Active field if it's non-nil, zero value otherwise.
func (i *Incident) GetActive() string {
	if i == nil || i.Active == nil {
		return ""
	}
	return *i.Active
}

// GetActivityDue returns the ActivityDue field if it's non-nil, zero value otherwise.
func (i *Incident) GetActivityDue() string {
	if i == nil || i.ActivityDue == nil {
		return ""
	}
	return *i.ActivityDue
}

// GetAdditionalAssigneeList returns the AdditionalAssigneeList field if it's non-nil, zero value otherwise.
func (i *Incident) GetAdditionalAssigneeList() string {
	if i == nil || i.AdditionalAssigneeList == nil {
		return ""
	}
	return *i.AdditionalAssigneeList
}

// GetApproval returns the Approval field if it's non-nil, zero value otherwise.
func (i *Incident) GetApproval() string {
	if i == nil || i.Approval == nil {
		return ""
	}
	return *i.Approval
}

// GetApprovalHistory returns the ApprovalHistory field if it's non-nil, zero value otherwise.
func (i *Incident) GetApprovalHistory() string {
	if i == nil || i.ApprovalHistory == nil {
		return ""
	}
	return *i.ApprovalHistory
}

// GetApprovalSet returns the ApprovalSet field if it's non-nil, zero value otherwise.
func (i *Incident) GetApprovalSet() string {
	if i == nil || i.ApprovalSet == nil {
		return ""
	}
	return *i.ApprovalSet
}

// GetAssignedTo returns the AssignedTo field if it's non-nil, zero value otherwise.
func (i *Incident) GetAssignedTo() string {
	if i == nil || i.AssignedTo == nil {
		return ""
	}
	return *i.AssignedTo
}

// GetAssignmentGroup returns the AssignmentGroup field if it's non-nil, zero value otherwise.
func (i *Incident) GetAssignmentGroup() string {
	if i == nil || i.AssignmentGroup == nil {
		return ""
	}
	return *i.AssignmentGroup
}

// GetBusinessDuration returns the BusinessDuration field if it's non-nil, zero value otherwise.
func (i *Incident) GetBusinessDuration() string {
	if i == nil || i.BusinessDuration == nil {
		return ""
	}
	return *i.BusinessDuration
}

// GetBusinessService returns the BusinessService field if it's non-nil, zero value otherwise.
func (i *Incident) GetBusinessService() string {
	if i == nil || i.BusinessService == nil {
		return ""
	}
	return *i.BusinessService
}

// GetBusinessStc returns the BusinessStc field if it's non-nil, zero value otherwise.
func (i *Incident) GetBusinessStc() string {
	if i == nil || i.BusinessStc == nil {
		return ""
	}
	return *i.BusinessStc
}

// GetCalendarDuration returns the CalendarDuration field if it's non-nil, zero value otherwise.
func (i *Incident) GetCalendarDuration() string {
	if i == nil || i.CalendarDuration == nil {
		return ""
	}
	return *i.CalendarDuration
}

// GetCalendarStc returns the CalendarStc field if it's non-nil, zero value otherwise.
func (i *Incident) GetCalendarStc() string {
	if i == nil || i.CalendarStc == nil {
		return ""
	}
	return *i.CalendarStc
}

// GetCallerID returns the CallerID field if it's non-nil, zero value otherwise.
func (i *Incident) GetCallerID() string {
	if i == nil || i.CallerID == nil {
		return ""
	}
	return *i.CallerID
}

// GetCategory returns the Category field if it's non-nil, zero value otherwise.
func (i *Incident) GetCategory() string {
	if i == nil || i.Category == nil {
		return ""
	}
	return *i.Category
}

// GetCausedBy returns the CausedBy field if it's non-nil, zero value otherwise.
func (i *Incident) GetCausedBy() string {
	if i == nil || i.CausedBy == nil {
		return ""
	}
	return *i.CausedBy
}

// GetChildIncidents returns the ChildIncidents field if it's non-nil, zero value otherwise.
func (i *Incident) GetChildIncidents() string {
	if i == nil || i.ChildIncidents == nil {
		return ""
	}
	return *i.ChildIncidents
}

// GetCloseCode returns the CloseCode field if it's non-nil, zero value otherwise.
func (i *Incident) GetCloseCode() string {
	if i == nil || i.CloseCode == nil {
		return ""
	}
	return *i.CloseCode
}

// GetClosedAt returns the ClosedAt field if it's non-nil, zero value otherwise.
func (i *Incident) GetClosedAt() string {
	if i == nil || i.ClosedAt == nil {
		return ""
	}
	return *i.ClosedAt
}

// GetClosedBy returns the ClosedBy field if it's non-nil, zero value otherwise.
func (i *Incident) GetClosedBy() string {
	if i == nil || i.ClosedBy == nil {
		return ""
	}
	return *i.ClosedBy
}

// GetCloseNotes returns the CloseNotes field if it's non-nil, zero value otherwise.
func (i *Incident) GetCloseNotes() string {
	if i == nil || i.CloseNotes == nil {
		return ""
	}
	return *i.CloseNotes
}

// GetCmdbCi returns the CmdbCi field if it's non-nil, zero value otherwise.
func (i *Incident) GetCmdbCi() string {
	if i == nil || i.CmdbCi == nil {
		return ""
	}
	return *i.CmdbCi
}

// GetComments returns the Comments field if it's non-nil, zero value otherwise.
func (i *Incident) GetComments() string {
	if i == nil || i.Comments == nil {
		return ""
	}
	return *i.Comments
}

// GetCommentsAndWorkNotes returns the CommentsAndWorkNotes field if it's non-nil, zero value otherwise.
func (i *Incident) GetCommentsAndWorkNotes() string {
	if i == nil || i.CommentsAndWorkNotes == nil {
		return ""
	}
	return *i.CommentsAndWorkNotes
}

// GetCompany returns the Company field if it's non-nil, zero value otherwise.
func (i *Incident) GetCompany() string {
	if i == nil || i.Company == nil {
		return ""
	}
	return *i.Company
}

// GetContactType returns the ContactType field if it's non-nil, zero value otherwise.
func (i *Incident) GetContactType() string {
	if i == nil || i.ContactType == nil {
		return ""
	}
	return *i.ContactType
}

// GetCorrelationDisplay returns the CorrelationDisplay field if it's non-nil, zero value otherwise.
func (i *Incident) GetCorrelationDisplay() string {
	if i == nil || i.CorrelationDisplay == nil {
		return ""
	}
	return *i.CorrelationDisplay
}

// GetCorrelationID returns the CorrelationID field if it's non-nil, zero value otherwise.
func (i *Incident) GetCorrelationID() string {
	if i == nil || i.CorrelationID == nil {
		return ""
	}
	return *i.CorrelationID
}

// GetDeliveryPlan returns the DeliveryPlan field if it's non-nil, zero value otherwise.
func (i *Incident) GetDeliveryPlan() string {
	if i == nil || i.DeliveryPlan == nil {
		return ""
	}
	return *i.DeliveryPlan
}

// GetDeliveryTask returns the DeliveryTask field if it's non-nil, zero value otherwise.
func (i *Incident) GetDeliveryTask() string {
	if i == nil || i.DeliveryTask == nil {
		return ""
	}
	return *i.DeliveryTask
}

// GetDescription returns the Description field if it's non-nil, zero value otherwise.
func (i *Incident) GetDescription() string {
	if i == nil || i.Description == nil {
		return ""
	}
	return *i.Description
}

// GetDueDate returns the DueDate field if it's non-nil, zero value otherwise.
func (i *Incident) GetDueDate() string {
	if i == nil || i.DueDate == nil {
		return ""
	}
	return *i.DueDate
}

// GetEscalation returns the Escalation field if it's non-nil, zero value otherwise.
func (i *Incident) GetEscalation() string {
	if i == nil || i.Escalation == nil {
		return ""
	}
	return *i.Escalation
}

// GetExpectedStart returns the ExpectedStart field if it's non-nil, zero value otherwise.
func (i *Incident) GetExpectedStart() string {
	if i == nil || i.ExpectedStart == nil {
		return ""
	}
	return *i.ExpectedStart
}

// GetFollowUp returns the FollowUp field if it's non-nil, zero value otherwise.
func (i *Incident) GetFollowUp() string {
	if i == nil || i.FollowUp == nil {
		return ""
	}
	return *i.FollowUp
}

// GetGroupList returns the GroupList field if it's non-nil, zero value otherwise.
func (i *Incident) GetGroupList() string {
	if i == nil || i.GroupList == nil {
		return ""
	}
	return *i.GroupList
}

// GetImpact returns the Impact field if it's non-nil, zero value otherwise.
func (i *Incident) GetImpact() string {
	if i == nil || i.Impact == nil {
		return ""
	}
	return *i.Impact
}

// GetIncidentState returns the IncidentState field if it's non-nil, zero value otherwise.
func (i *Incident) GetIncidentState() string {
	if i == nil || i.IncidentState == nil {
		return ""
	}
	return *i.IncidentState
}

// GetKnowledge returns the Knowledge field if it's non-nil, zero value otherwise.
func (i *Incident) GetKnowledge() string {
	if i == nil || i.Knowledge == nil {
		return ""
	}
	return *i.Knowledge
}

// GetLocation returns the Location field if it's non-nil, zero value otherwise.
func (i *Incident) GetLocation() string {
	if i == nil || i.Location == nil {
		return ""
	}
	return *i.Location
}

// GetMadeSLA returns the MadeSLA field if it's non-nil, zero value otherwise.
func (i *Incident) GetMadeSLA() string {
	if i == nil || i.MadeSLA == nil {
		return ""
	}
	return *i.MadeSLA
}

// GetNotify returns the Notify field if it's non-nil, zero value otherwise.
func (i *Incident) GetNotify() string {
	if i == nil || i.Notify == nil {
		return ""
	}
	return *i.Notify
}

// GetNumber returns the Number field if it's non-nil, zero value otherwise.
func (i *Incident) GetNumber() string {
	if i == nil || i.Number == nil {
		return ""
	}
	return *i.Number
}

// GetOpenedAt returns the OpenedAt field if it's non-nil, zero value otherwise.
func (i *Incident) GetOpenedAt() string {
	if i == nil || i.OpenedAt == nil {
		return ""
	}
	return *i.OpenedAt
}

// GetOpenedBy returns the OpenedBy field if it's non-nil, zero value otherwise.
func (i *Incident) GetOpenedBy() string {
	if i == nil || i.OpenedBy == nil {
		return ""
	}
	return *i.OpenedBy
}

// GetOrder returns the Order field if it's non-nil, zero value otherwise.
func (i *Incident) GetOrder() string {
	if i == nil || i.Order == nil {
		return ""
	}
	return *i.Order
}

// GetParent returns the Parent field if it's non-nil, zero value otherwise.
func (i *Incident) GetParent() string {
	if i == nil || i.Parent == nil {
		return ""
	}
	return *i.Parent
}

// GetParentIncident returns the ParentIncident field if it's non-nil, zero value otherwise.
func (i *Incident) GetParentIncident() string {
	if i == nil || i.ParentIncident == nil {
		return ""
	}
	return *i.ParentIncident
}

// GetPriority returns the Priority field if it's non-nil, zero value otherwise.
func (i *Incident) GetPriority() string {
	if i == nil || i.Priority == nil {
		return ""
	}
	return *i.Priority
}

// GetProblemID returns the ProblemID field if it's non-nil, zero value otherwise.
func (i *Incident) GetProblemID() string {
	if i == nil || i.ProblemID == nil {
		return ""
	}
	return *i.ProblemID
}

// GetReassignmentCount returns the ReassignmentCount field if it's non-nil, zero value otherwise.
func (i *Incident) GetReassignmentCount() string {
	if i == nil || i.ReassignmentCount == nil {
		return ""
	}
	return *i.ReassignmentCount
}

// GetRejectionGoto returns the RejectionGoto field if it's non-nil, zero value otherwise.
func (i *Incident) GetRejectionGoto() string {
	if i == nil || i.RejectionGoto == nil {
		return ""
	}
	return *i.RejectionGoto
}

// GetReopenCount returns the ReopenCount field if it's non-nil, zero value otherwise.
func (i *Incident) GetReopenCount() string {
	if i == nil || i.ReopenCount == nil {
		return ""
	}
	return *i.ReopenCount
}

// GetResolvedAt returns the ResolvedAt field if it's non-nil, zero value otherwise.
func (i *Incident) GetResolvedAt() string {
	if i == nil || i.ResolvedAt == nil {
		return ""
	}
	return *i.ResolvedAt
}

// GetResolvedBy returns the ResolvedBy field if it's non-nil, zero value otherwise.
func (i *Incident) GetResolvedBy() string {
	if i == nil || i.ResolvedBy == nil {
		return ""
	}
	return *i.ResolvedBy
}

// GetRfc returns the Rfc field if it's non-nil, zero value otherwise.
func (i *Incident) GetRfc() string {
	if i == nil || i.Rfc == nil {
		return ""
	}
	return *i.Rfc
}

// GetSeverity returns the Severity field if it's non-nil, zero value otherwise.
func (i *Incident) GetSeverity() string {
	if i == nil || i.Severity == nil {
		return ""
	}
	return *i.Severity
}

// GetShortDescription returns the ShortDescription field if it's non-nil, zero value otherwise.
func (i *Incident) GetShortDescription() string {
	if i == nil || i.ShortDescription == nil {
		return ""
	}
	return *i.ShortDescription
}

// GetSLADue returns the SLADue field if it's non-nil, zero value otherwise.
func (i *Incident) GetSLADue() string {
	if i == nil || i.SLADue == nil {
		return ""
	}
	return *i.SLADue
}

// GetState returns the State field if it's non-nil, zero value otherwise.
func (i *Incident) GetState() string {
	if i == nil || i.State == nil {
		return ""
	}
	return *i.State
}

// GetStatus returns the Status field if it's non-nil, zero value otherwise.
func (i *Incident) GetStatus() string {
	if i == nil || i.Status == nil {
		return ""
	}
	return *i.Status
}

// GetSubcategory returns the Subcategory field if it's non-nil, zero value otherwise.
func (i *Incident) GetSubcategory() string {
	if i == nil || i.Subcategory == nil {
		return ""
	}
	return *i.Subcategory
}

// GetSysClassName returns the SysClassName field if it's non-nil, zero value otherwise.
func (i *Incident) GetSysClassName() string {
	if i == nil || i.SysClassName == nil {
		return ""
	}
	return *i.SysClassName
}

// GetSysCreatedBy returns the SysCreatedBy field if it's non-nil, zero value otherwise.
func (i *Incident) GetSysCreatedBy() string {
	if i == nil || i.SysCreatedBy == nil {
		return ""
	}
	return *i.SysCreatedBy
}

// GetSysCreatedOn returns the SysCreatedOn field if it's non-nil, zero value otherwise.
func (i *Incident) GetSysCreatedOn() string {
	if i == nil || i.SysCreatedOn == nil {
		return ""
	}
	return *i.SysCreatedOn
}

// GetSysDomain returns the SysDomain field if it's non-nil, zero value otherwise.
func (i *Incident) GetSysDomain() string {
	if i == nil || i.SysDomain == nil {
		return ""
	}
	return *i.SysDomain
}

// GetSysDomainPath returns the SysDomainPath field if it's non-nil, zero value otherwise.
func (i *Incident) GetSysDomainPath() string {
	if i == nil || i.SysDomainPath == nil {
		return ""
	}
	return *i.SysDomainPath
}

// GetSysID returns the SysID field if it's non-nil, zero value otherwise.
func (i *Incident) GetSysID() string {
	if i == nil || i.SysID == nil {
		return ""
	}
	return *i.SysID
}

// GetSysModCount returns the SysModCount field if it's non-nil, zero value otherwise.
func (i *Incident) GetSysModCount() string {
	if i == nil || i.SysModCount == nil {
		return ""
	}
	return *i.SysModCount
}

// GetSysTags returns the SysTags field if it's non-nil, zero value otherwise.
func (i *Incident) GetSysTags() string {
	if i == nil || i.SysTags == nil {
		return ""
	}
	return *i.SysTags
}

// GetSysUpdatedBy returns the SysUpdatedBy field if it's non-nil, zero value otherwise.
func (i *Incident) GetSysUpdatedBy() string {
	if i == nil || i.SysUpdatedBy == nil {
		return ""
	}
	return *i.SysUpdatedBy
}

// GetSysUpdatedOn returns the SysUpdatedOn field if it's non-nil, zero value otherwise.
func (i *Incident) GetSysUpdatedOn() string {
	if i == nil || i.SysUpdatedOn == nil {
		return ""
	}
	return *i.SysUpdatedOn
}

// GetTimeWorked returns the TimeWorked field if it's non-nil, zero value otherwise.
func (i *Incident) GetTimeWorked() string {
	if i == nil || i.TimeWorked == nil {
		return ""
	}
	return *i.TimeWorked
}

// GetUponApproval returns the UponApproval field if it's non-nil, zero value otherwise.
func (i *Incident) GetUponApproval() string {
	if i == nil || i.UponApproval == nil {
		return ""
	}
	return *i.UponApproval
}

// GetUponReject returns the UponReject field if it's non-nil, zero value otherwise.
func (i *Incident) GetUponReject() string {
	if i == nil || i.UponReject == nil {
		return ""
	}
	return *i.UponReject
}

// GetUrgency returns the Urgency field if it's non-nil, zero value otherwise.
func (i *Incident) GetUrgency() string {
	if i == nil || i.Urgency == nil {
		return ""
	}
	return *i.Urgency
}

// GetUserInput returns the UserInput field if it's non-nil, zero value otherwise.
func (i *Incident) GetUserInput() string {
	if i == nil || i.UserInput == nil {
		return ""
	}
	return *i.UserInput
}

// GetWatchList returns the WatchList field if it's non-nil, zero value otherwise.
func (i *Incident) GetWatchList() string {
	if i == nil || i.WatchList == nil {
		return ""
	}
	return *i.WatchList
}

// GetWfActivity returns the WfActivity field if it's non-nil, zero value otherwise.
func (i *Incident) GetWfActivity() string {
	if i == nil || i.WfActivity == nil {
		return ""
	}
	return *i.WfActivity
}

// GetWorkEnd returns the WorkEnd field if it's non-nil, zero value otherwise.
func (i *Incident) GetWorkEnd() string {
	if i == nil || i.WorkEnd == nil {
		return ""
	}
	return *i.WorkEnd
}

// GetWorkNotes returns the WorkNotes field if it's non-nil, zero value otherwise.
func (i *Incident) GetWorkNotes() string {
	if i == nil || i.WorkNotes == nil {
		return ""
	}
	return *i.WorkNotes
}

// GetWorkNotesList returns the WorkNotesList field if it's non-nil, zero value otherwise.
func (i *Incident) GetWorkNotesList() string {
	if i == nil || i.WorkNotesList == nil {
		return ""
	}
	return *i.WorkNotesList
}

// GetWorkStart returns the WorkStart field if it's non-nil, zero value otherwise.
func (i *Incident) GetWorkStart() string {
	if i == nil || i.WorkStart == nil {
		return ""
	}
	return *i.WorkStart
}
